language: generic

sudo: required

# Travis CI에게 Docker환경에서 구동됨을 명시
services:
  - docker

# 운영모드 이미지 빌드 전 frontend (react) 테스트를 위한 이미지 빌드
before_install:
  - docker build -t zbeld123/react-test -f ./frontend/Dockerfile.dev ./frontend

# 테스트 수행 Travis CI에서 수행됨
script:
  - docker run -e CI=true zbeld123/react-test npm run test

# 운영모드 이미지 빌드 및 Docker hubd에 push
after_success:
  - docker build -t zbeld123/docker-frontend ./frontend
  - docker build -t zbeld123/docker-backend ./backend
  - docker build -t zbeld123/docker-nginx ./nginx
  # Docker hub에 로그인
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  # Docker hub에 push
  - docker push zbeld123/docker-frontend
  - docker push zbeld123/docker-backend
  - docker push zbeld123/docker-nginx


# 배포
deploy:
  provider:  elasticbeanstalk         # 외부 서비스 명시 EB, S3, Firebase ...
  region:  "ap-northeast-2"           # AWS의 물리적 위치 
  app: "docker-fullstack-app"         # 생성된 애플리케이션 이름
  env:  "Dockerfullstackapp-env"      # 환경 이름
  bucket_name:  elasticbeanstalk-ap-northeast-2-771839060615 # S3 bucket name
    bucket_path:  "docker-fullstack-app"  # 애플리케이션 이름과 동일
  on:
    branch:  master                   # 어떤 brach에서 배포를 수행할 지 설정  
  access_key_id: $AWS_ACCESS_KEY      # AWS IAM access key (TraviaCI에 등록된)
  secret_access_key: $AWS_SECRET_ACCESS_KEY # AWS IAM secret access key (TraviaCI에 등록된)