version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306

  nginx:
    restart: always # 재시작 정책 (항상 재식작)
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped # 재시작 정책 (임의로 멈추지 않는 이상 항상 재시작)
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "1234"
  #     MYSQL_DATABASE: myapp
